### ISSUE TITLE
Cannot install version 0.9.7 with pip3

### ISSUE THREAD

**Issue by eamarten** [dpranke/pyjson5#55] opened 2022-05-07 18:54 UTC
$ pip3 install -U json5                           
Requirement already satisfied: json5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (0.9.6)
Collecting json5
  Using cached json5-0.9.7.tar.gz (22 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'entry_points'
        warnings.warn(msg)
      /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'install_requires'
        warnings.warn(msg)
      /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'extras_require'
        warnings.warn(msg)
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
      
      error: invalid command 'egg_info'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by dpranke** [comment] 2022-05-09 01:58
Looks like maybe this is a 3.10 issue? v0.9.8, at least, installed fine for me on 3.9 (and I would expect it to have the same problem as v0.9.7).

I know they've been changing how to do a bunch of things in the distribution code and I need to do some reading.

Did prior versions (e.g., v0.9.6) work for you?

**Comment by eamarten** [comment] 2022-05-09 07:26
Thank you for looking into this. Indeed, I can install 0.9.6 but neither 0.9.7 nor 0.9.8.

**Comment by dpranke** [comment] 2022-05-09 16:01
Okay, I installed the latest python3 from python.org (3.10.4), ran `pip3 install --upgrade pip` and `pip3 install --upgrade setuptools`, and then ran `pip3 install -Uv 'json5==0.9.7' and it installed fine.

I suspect there's something weird going on with your setuptools install. Doing the above left me with pip-22.0.4 and setuptools-62.1.0. What versions do you have? 

The only change to the install from v0.9.7 and above was fixing a typo in the classifiers. I wouldn't expect that to have affected anything, so I'm not sure what might be going on otherwise.

**Comment by eamarten** [comment] 2022-05-09 17:29
I have the same versions of both pip and setuptools. I had no issue installing or upgrading packages so far. Puzzling indeed...

**Comment by eamarten** [comment] 2022-05-09 19:26
That makes no difference:
$ pip3 check               
jupyterlab-server 2.13.0 requires json5, which is not installed.
$ pip3 install json5==0.9.7
Collecting json5==0.9.7
  Using cached json5-0.9.7.tar.gz (22 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'entry_points'
        warnings.warn(msg)
      /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'install_requires'
        warnings.warn(msg)
      /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'extras_require'
        warnings.warn(msg)
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
      
      error: invalid command 'egg_info'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by dpranke** [comment] 2022-05-10 22:31
Hmm. 

I spent a good amount of time today trying to trace through the setuptools logic to understand how/when that message might be printed, but didn't get an answer. I.e., I don't know how you're getting into that state, but there's also weirdness going on in setuptools that I don't understand and don't really have the time to dig into.

My best guess is that there's something messed up in your Python installation, such that things are out of sync.

Is it possible for you to reinstall Python and/or make sure you have a clean install?

If not, I'm not sure how to make progress on this bug. I don't know that I can spend a lot more time on it unless others are also hitting this. And if other people are hitting it, please speak up.

**Comment by dpranke** [comment] 2022-05-10 22:34
It looks like the packaging community wants to substantially change how stuff is packaged (moving to pyproject.toml and such). I'm not up-to-speed on that yet, but maybe if I can switch how the install works, this'll just go away then.

**Comment by eamarten** [comment] 2022-05-11 06:38
Reinstalling Python dis not change things. Many thanks for all the time you spent on this; indeed if you have no access to an environment that triggers that behaviour then addressing the issue is close to impossible. I very much appreciate that you did everything you could.

**Comment by eamarten** [comment] 2022-05-17 04:38
Just installed the new setuptools-62.3.0, tried again without hoping much, but it worked!

$ pip3 install -U json5    
Requirement already satisfied: json5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (0.9.6)
Collecting json5
  Using cached json5-0.9.8.tar.gz (22 kB)
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for json5, since package 'wheel' is not installed.
Installing collected packages: json5
  Attempting uninstall: json5
    Found existing installation: json5 0.9.6
    Uninstalling json5-0.9.6:
      Successfully uninstalled json5-0.9.6
  Running setup.py install for json5 ... done
Successfully installed json5-0.9.8

**Comment by dpranke** [comment] 2022-05-17 16:23
Thanks for the update. I'm going to guess that there was some regression in setuptools that you were somehow hitting, and the newest version of setuptools fixed it.

I'm going to close this now, but I'd be happy to reopen if we think there's something I can do to change the code to avoid it (apart from reworking the package to use pyproject et al, which is more work than this bug can track.

**Closed by dpranke** 2022-05-17 16:23 UTC

**Comment by dpranke** [comment] 2022-05-18 18:08
Another note on this:

By downloading the installer from Python.org, I get a `/usr/local/bin/python3` that returns `3.10.4` for `python --version`. This includes version `22.0.4` of pip and version `58.1.0` of setuptools. 

Running `python3 -m pip install --upgrade pip` gets me to `22.1` but leaves setuptools alone. 

Running `python3 -m pip install --upgrade setuptools` gets me `setuptools-62.3.1'.

Downgrading setuptools via `pip install --force-reinstall setuptools=62.1.0`, I can then **still** install json5 just fine.

So, I don't know what was going on in your install, but it would be interesting to see if you could reproduce the issue doing something like what I was doing.

Then again, if you're happy enough that it's working now, there's no need to do more troubleshooting unless someone else also hits a problem like this and can't get it working.

**Comment by eamarten** [comment] 2022-05-19 12:47
I did what you did and it triggered the same issue with setuptools=62.1.0... On MacOS Monterey 12.4. We sure always dislike it when we do not understand the sources of error and I understand it bugs you! I sure am happy it is working now, but I am also puzzled no one seems to have hit that problem...

**Comment by dpranke** [comment] 2022-05-19 20:52
Are you by chance running an ARM/M1 Mac, rather than an Intel-based Mac? I'm using an Intel-based Mac. `json5` is a pure Python package, so I wouldn't expect that to matter, but I'm grasping at straws here ...

**Comment by eamarten** [comment] 2022-05-19 22:29
No, Intel-based.
